### ISSUE TITLE
GROUP QUESTION: How will new election data be delivered? Do we need a streaming API?

### ISSUE THREAD

**Issue by NathanLawrence** [gordonje/mo_election_night_2016#13]
Hi All,

This is something I neglected to mention at our meeting, but it's fairly important, so I thought I would take the time to write a little thing up about it now. This is for everyone, but especially folks who will be working on the front-end at the Missourian (since I'll be handling the KBIA one).

How do you plan on handling new election results? Will users be expected to refresh to see new results, or would you like to be pulling them into your visualizations automatically? I think that in 2016, pulling results in automatically throughout the night while the same page is open is not just an opportunity to delight the user with convenience and a smooth experience; it's becoming a default expectation.

This is an interesting complication, because suddenly not only do you have to handle page load requests, but every page with election results will continue needing data long after it has first loaded. If you're going to initiate new HTTP requests on a regular basis, that's a lot of requests our infrastructure will suddenly be handling. 

Luckily, this problem is not unique to election results. Lots of modern web services face the problem of users needing to see a constantly changing collection of data as quickly as possible -- take Twitter or Facebook. Imagine how annoying it would be if you needed to refresh Facebook every time you wanted to see new comments. Because of these concerns, a number of accepted best practices and standards have emerged to handle these situations over the last decade.

As is often the case with these sorts of problems, there's what's often considered the "right" way, and there's an easy way. I honestly think that we can get away with the easy way this time (especially because of our infrastructure, which I'll get to), but I want to present you all with the options that you would be facing in a real-world production environment so you're prepared when someone asks you a similar question some day.

**The "Right" Way: Using WebSocket to Create a Streaming API**

In a traditional HTTP context, when the user visits the page, they send a request for information, perform a handshake with the server, get that information, then close the connection, effectively terminating all communication between the two devices. This is very efficient for static data, like web pages or user profile information. However, the moment you start needing to check one of these on a regular basis, to major problems occur: First, you aren't getting the data exactly when it changes -- you're waiting a given interval and checking back for changes instead -- and second, you're creating an unnecessary burden on the server by forcing it to process the initial request and perform the handshake every single time you want information.

In a streaming API over WebSocket (the same kind of API services like Twitter and Facebook use to present content feeds), an initial request is sent the same way over HTTP, but during the handshake, the client and server agree to switch protocols from HTTP to a protocol called WebSocket, which keeps a connection alive between the client and server. When data changes, the server just sends the new data through this open connection. It's much more efficient in a traditional client and server environment, but it's much more challenging to implement.

Some reasons we might shy away from this approach:
- It's a challenge to implement. It will probably take me 4-5 times as much time to create as a traditional HTTP API. 
- In the current Access Missouri setup, it will also be more expensive to maintain, since I'll have to roll out a traditional load balanced server infrastructure in addition to the on-demand one the normal API set I maintain uses.
- Handling streaming data in JavaScript requires an extra set of skills that many of you are probably unfamiliar with. I would recommend using [observables](http://reactivex.io/rxjs/) to handle these, which means that in addition to learning how to handle TopoJSON and mapping in D3, you'll have to cope with a whole new approach to data. 

**The Easy Way: Timed Polling on the Current Infrastructure**

This would be exactly what it sounds like. Instead of grabbing election results from an open connection to the server, we would agree together on a reasonable interval that our apps should use to make fresh HTTP requests for new data, then just compare that against the existing data and change the visualizations if the data has changed. 

As I said above, normally, this is a significant burden on a server, and it will create slight delays in getting election results to people's computers (for example, an interval of 60 seconds means people could get results up to 60 seconds after results have changed), but our infrastructure is set up to use on-demand computing resources that expand as needed, and the NoSQL database service that we'll be storing the election data inside is basically infinitely pollable, so the server burden shouldn't be a concern.

What are your thoughts? Are we safe implementing the normal HTTP API and agreeing on a reasonable refresh interval?

**Comment by gordonje** [comment]
All good thoughts. 

One piece of information that would clarify the choice is how often the results are updated by the Secretary of State. This might also determine how often we run the Python script that fetches and stores the results.

Looking back at 2014 data, the value in the `LastUpdated` attribute on one of the top-level tags in the XML is very precise:

``` xml
<?xml version="1.0" encoding="utf-8"?>
<ElectionResults LastUpdated="11/4/2014 7:57:42 PM" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<ElectionInfo>
<ElectionName>State of Missouri - General Election, November  04, 2014</ElectionName>
<ElectionDate>11/04/14</ElectionDate>
```

Generally, though, I don't think anyone is gonna be mad about a one minute delay.

**Comment by NathanLawrence** [comment]
Interesting. I was assuming we would need to be using MDA5 hashes to check if the results have been updated. It's good to know that's there.

**Comment by gordonje** [comment]
![Alt text](http://img.qdaily.com/uploads/20160714112421TV4Z5m2KpAacGnH8.gif-w600Gif)
