### ISSUE TITLE
Import 2014 XML data

### ISSUE THREAD

**Issue by gordonje** [gordonje/mo_election_night_2016#3]
Will be useful for testing purposes, until we get test data via the APfeed.

**Comment by NathanLawrence** [comment]
My suggested structure:

Use a function that takes in an elections results URL as string. Inside that function, parse the XML out into a nice, clean Python dict (object type ducked from `var = {}`), then push that out wherever you need it with Python's built-in json.dumps(dict) function.

**Comment by gordonje** [comment]
Actually, we can just get this from the old repo: https://raw.githubusercontent.com/gordonje/MO_votes_2014/master/data/feed_data.xml
