### ISSUE TITLE
Acquire shape data

### ISSUE THREAD

**Issue by gordonje** [gordonje/mo_election_night_2016#9]
Here is a [great walk-through](https://medium.com/@ccanipe/building-a-u-s-election-basemap-with-d3-js-and-topojson-fa4b5ab5175d#.xzvp1a11c) from the legendary @chriscanipe.

He suggests downloading the shape data from the [US Census website](https://www.census.gov/geo/maps-data/data/tiger-cart-boundary.html) and using a command-line utility to convert to topoJSON.

Then I believe we could probably just save it in the same dynamoDB instance as the rest of the election results.

**Comment by gordonje** [comment]
So...the county and congressional districts is already done and available [here](https://raw.githubusercontent.com/travishartman/elex/master/data/mo_topo_county.json)

But we need to download the congressional and state legislative districts:
- [ ]  Install the [command-line utility](https://github.com/mbostock/topojson/wiki/Command-Line-Reference) for converting to topoJSON (use npm of installation)
- [ ] Download the Missouri [state legislative district files](https://www.census.gov/geo/maps-data/data/cbf/cbf_sld.html) (we want as many years back as we can get).
- [ ] Download the [congressional district](https://www.census.gov/geo/maps-data/data/cbf/cbf_cds.html) shape file (again, as many years back as we can get)
- [ ] Run the commands (basically, read the tutorial and do what it says)
- [ ] Save each map (year and district type) as its own topoJSON file

**Comment by NathanLawrence** [comment]
Sorry to resurrect these -- I seem to remember this was completed and we had tons of them. I'd love to archive them for future use. Any idea where they wound up, anyone?

**Comment by NathanLawrence** [comment]
Nevermind. Looks like they're in this repo.
